# Build customization
builds:
  - binary: terragrunt
    ldflags: -s -w -X main.VERSION={{.Version}}_Coveo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

# Archive customization
archive:
  format: zip

  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS

  files:
    - nothing.*
