language: go
go:
- 1.8.x

sudo: false

before_install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    go get github.com/Masterminds/glide &&
    go install github.com/Masterminds/glide &&
    cd ../.. &&
    mv coveo gruntwork-io &&
    cd gruntwork-io/terragrunt &&
  fi

install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    cp glide.lock glide.original &&
    glide up &&
    mv glide.original glide.lock;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi

notifications:
  email: false
